CREATE TABLE plots (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  slots_time INT NULL,
  crop_type varchar (100) NULL,
  area FLOAT NOT NULL,
  device_id INT NULL,
  created_date DATE NOT NULL,
  modified_date DATE NOT NULL,
  CONSTRAINT plot_pkey PRIMARY KEY (id)
);
