CREATE TABLE devices (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  serial_num varchar (50) NOT NULL,
  status varchar (10) NOT NULL,
  availability varchar (10) NOT NULL,
  alert_email varchar (100) NULL,
  alert_phone varchar (30) NULL,
  created_date DATE NOT NULL,
  modified_date DATE NOT NULL,
  CONSTRAINT device_pkey PRIMARY KEY (id),
  CONSTRAINT device_sn_uniq_key UNIQUE (serial_num)
);
